Kibana Docker - Sleep

diff --git a/so-kibana/bin/kibana-docker b/so-kibana/bin/kibana-docker
--- a/so-kibana/bin/kibana-docker
+++ b/so-kibana/bin/kibana-docker
@@ -11,28 +11,29 @@
 #
 #       --elasticsearch.startupTimeout=60
 # Wait for ElasticSearch to come up, so that we can query for version infromation
-echo -n "Waiting for ElasticSearch..."
-COUNT=0
-ELASTICSEARCH_CONNECTED="no"
-while [[ "$COUNT" -le 30 ]]; do
-  curl --output /dev/null --silent --head --fail http://$ELASTICSEARCH_HOST:9200
-  if [ $? -eq 0 ]; then
-    ELASTICSEARCH_CONNECTED="yes"
-    echo "connected to $ELASTICSEARCH_HOST !" >> /var/log/kibana/esstartup.log
-    break
-  else
-    ((COUNT+=1))
-    sleep 1
-    echo -n "."
-  fi
-done
-if [ "$ELASTICSEARCH_CONNECTED" == "no" ]; then
-  echo
-  echo -e "Connection attempt timed out.  $ELASTICSEARCH_HOST Unable to connect to ElasticSearch.  \nPlease try: \n  -checking log(s) in /var/log/elasticsearch/\n  -running 'sudo docker ps' \n  -running 'sudo so-elastic-restart'" >> /var/log/kibana/esstartup.log
-  echo
-
-  exit
-fi
+#echo -n "Waiting for ElasticSearch..."
+#COUNT=0
+#ELASTICSEARCH_CONNECTED="no"
+#while [[ "$COUNT" -le 30 ]]; do
+#  curl --output /dev/null --silent --head --fail http://$ELASTICSEARCH_HOST:9200
+#  if [ $? -eq 0 ]; then
+#    ELASTICSEARCH_CONNECTED="yes"
+#    echo "connected to $ELASTICSEARCH_HOST !" >> /var/log/kibana/esstartup.log
+#    break
+#  else
+#    ((COUNT+=1))
+#    sleep 1
+#    echo -n "."
+#  fi
+#done
+#if [ "$ELASTICSEARCH_CONNECTED" == "no" ]; then
+#  echo
+#  echo -e "Connection attempt timed out.  $ELASTICSEARCH_HOST Unable to connect to ElasticSearch.  \nPlease try: \n  -checking log(s) in /var/log/elasticsearch/\n  -running 'sudo docker ps' \n  -running 'sudo so-elastic-restart'" >> /var/log/kibana/esstartup.log
+#  echo
+#
+#  exit
+#fi
+sleep 30
 
 kibana_vars=(
     console.enabled
